- name: inventory level variables
  hosts: frontend
  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: " inventory level Hello {{ COURSE }} course, duration {{ DURATION }}, trainer {{ TRAINER }} "