- name: checking vars prefererence
  hosts: local
  connection: local
  vars:
   varcheck: from vars play
  vars_files:
   - course.yaml
  vars_prompt:
  - name: varcheck
    prompt: please enter varcheck
    private: false
   
  tasks:
   - name: print check 
     vars:
       varcheck: from tasks
     ansible.builtin.debug:
      msg: "{{ varcheck }} "