- name: checking vars prefererence
  hosts: local
  connection: local
  vars:
   varcheck: from vars play
  vars_files:
   - course.yaml
  vars_prompt:
   - name: varcheck
     prompt: enter the prompt:
     private: false
   
  tasks:
   - name: print course information
     vars:
       varcheck: from tasks
     ansible.builtin.debug:
      msg: "{{ COURSE }}  "